version: '3'

services:
  db:
    build: ./db
    image: sachinsahoo/udb
    ports:
      - 5430:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: inventory

  api:
    build: ./spring-boot-multitenant
    image: sachinsahoo/uapi
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=inventory
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ##command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005 -Djava.security.egd=file:/dev/./urandom -jar /urvaru/spring-boot-multitenant/target/smulti.war


  client:
    build: ./u-client
    image: sachinsahoo/uclient
    ports:
      - 4000:80

volumes:
  pgdata: